// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxi3aO8zKun0MnB-hU2VU6QmUt1LK7SvM',
    appId: '1:1020977954182:web:4710354abba5f74ab14007',
    messagingSenderId: '1020977954182',
    projectId: 'learntounsi-7d90b',
    authDomain: 'learntounsi-7d90b.firebaseapp.com',
    storageBucket: 'learntounsi-7d90b.firebasestorage.app',
    measurementId: 'G-3FHKFHB77X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUgsbAlURd42qGEKHpphHS1BLXIPXVdBY',
    appId: '1:1020977954182:android:a65fc85e975c97e9b14007',
    messagingSenderId: '1020977954182',
    projectId: 'learntounsi-7d90b',
    storageBucket: 'learntounsi-7d90b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKj6ex5lxw4v9Ttk1o9V7LwR604-u2cbA',
    appId: '1:1020977954182:ios:0e98e087006aa7d5b14007',
    messagingSenderId: '1020977954182',
    projectId: 'learntounsi-7d90b',
    storageBucket: 'learntounsi-7d90b.firebasestorage.app',
    iosBundleId: 'com.example.learntounsiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKj6ex5lxw4v9Ttk1o9V7LwR604-u2cbA',
    appId: '1:1020977954182:ios:0e98e087006aa7d5b14007',
    messagingSenderId: '1020977954182',
    projectId: 'learntounsi-7d90b',
    storageBucket: 'learntounsi-7d90b.firebasestorage.app',
    iosBundleId: 'com.example.learntounsiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxi3aO8zKun0MnB-hU2VU6QmUt1LK7SvM',
    appId: '1:1020977954182:web:4710354abba5f74ab14007',
    messagingSenderId: '1020977954182',
    projectId: 'learntounsi-7d90b',
    authDomain: 'learntounsi-7d90b.firebaseapp.com',
    storageBucket: 'learntounsi-7d90b.firebasestorage.app',
    measurementId: 'G-3FHKFHB77X',
  );
}
